version: '3.8'


services:
  #Servicio de PHP + Apache
  app:
    container_name: Cine_app
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - crud-network

#Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: cine_mysql
    environment:
    #Datos de conexion
      MYSQL_ROOT_PASSWORD: grupo4
      MYSQL_DATABASE: cine_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crud-network
networks:
  crud-network:
    driver: bridge
volumes:
  db-data: